- hosts: all
  become: yes
  tasks:
    - name: Add SSH Key for ansible user
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
