- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: install httpd service
      yum:
        name: httpd
        state: present
    - name: copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 0777
        owner: ansible
        group: ansible
    - name: Start and Enabled httpd service
      service:
        name: httpd
        state: started
        enabled: yes
