- hosts: jenkinsserver
  become: true
  tasks:

    - name: Install Amazon Corretto 17
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Set Java 17 as default
      alternatives:
        name: java
        path: /usr/lib/jvm/java-17-amazon-corretto/bin/java

    - name: Verify Java Version
      command: java -version
      register: java_version
      changed_when: false

    - name: Print Java Version
      debug:
        var: java_version.stdout

    - name: Download Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins RPM key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Start Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        delay: 30

    - name: Get Initial Admin Password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkinspass
      changed_when: false

    - name: Print Jenkins Admin Password
      debug:
        var: jenkinspass.stdout
